- type: entity
  id: AU14LanguagePresetXeno
  name: Xenoish Language
  categories: [ HideSpawnMenu ]
  components:
  - type: LanguagePreset
    spokenLanguages:
    - English
    - Xeno
    understoodLanguages:
    - English
    - Xeno
    currentLanguage: English
    defaultLanguage: English

- type: entity
  id: AU14LanguagePresetYautja
  name: Yautja Language
  categories: [ HideSpawnMenu ]
  components:
  - type: LanguagePreset
    spokenLanguages:
    - English
    - Yautja
    understoodLanguages:
    - English
    - Yautja
    currentLanguage: English
    defaultLanguage: English

- type: entity
  id: AU14LanguagePresetArcturian
  name: Arcturian Language
  categories: [ HideSpawnMenu ]
  components:
  - type: LanguagePreset
    spokenLanguages:
    - English
    - Arcturian
    understoodLanguages:
    - English
    - Arcturian
    currentLanguage: Arcturian
    defaultLanguage: Arcturian

- type: entity
  id: CMUPathogenLanguagePreset
  name: Pathogen Language
  categories: [ HideSpawnMenu ]
  components:
  - type: Language
    spokenLanguages:
    - Pathogen
    understoodLanguages:
    - Pathogen
    currentLanguage: Pathogen
    defaultLanguage: Pathogen