- type: entity
  parent: CMMobHuman
  id: AU14BaseMobSpeciesOrganicUNISC
  suffix: AU14, UNISC
  abstract: true
  components:
  - type: GhostTakeoverAvailable
  - type: NpcFactionMember
    factions:
    - AUUnitedAmericas
  - type: RandomHumanoidAppearance
  - type: RandomHumanoidAppearanceWhitelisted
    allowedMaleHairStyles:
    - RMCHumanHairCrew
    - RMCHumanHairAviator
    - RMCHumanHairJensen
    - RMCHumanHairAverageJoe
    - AU14HumanHairCIA5
    - RMCHumanHairCombover
    - RMCHumanHairCombover2
    - RMCHumanHairCplDietrich
    - RMCHumanHairCut
    - RMCHumanHairHeadStubble
    - RMCHumanHairHighAndTight
    - RMCHumanHairHighfade
    - RMCHumanHairHighlight
    - AU14HumanHairIRS
    - RMCHumanHairLtRasczak
    - RMCHumanHairMarineFade
    - RMCHumanHairMarineFlatTop
    - RMCHumanHairMedfade
    - RMCHumanHairNofade
    - RMCHumanHairShavedpart
    - RMCHumanHairShavedHead
    - RMCHumanHairShort
    - RMCHumanHairSideUndercutHang
    - RMCHumanHairSkinhead
    - RMCHumanHairTaper
    - RMCHumanHairWardaddy
    - RMCHumanHairUndercut
    - RMCHumanHairUndercutTop
    allowedFemaleHairStyles:
    - RMCHumanHairShortbangs
    - RMCHumanHairBobcurl
    - RMCHumanHairMarineBun
    - RMCHumanHairBun
    - RMCHumanHairFringetail
    - AU14HumanHairLowBun
    - AU14HumanHairLowPonyTail
    - AU14HumanHairLowPonyTailAlt
    - RMCHumanHairPonytail1
    - RMCHumanHairPonytail7
    - RMCHumanHairPvtRedding
    - RMCHumanHairPvtVasquez
    - RMCHumanHairLong
    - RMCHumanHairPixieCutLeft
    - RMCHumanHairPixieCutRight
    allowedHairColorsHex:
    - "#0B0B0B"
    - "#1A1A1A"
    - "#222222"
    - "#2B1B0F"
    - "#3B2314"
    - "#4A2E1A"
    - "#5A3A22"
    - "#6B4A2F"
    - "#9C8651"
    - "#B79A5A"
    - "#4A1F12"
    - "#7A5E42"
    allowedEyeColorsHex: [ "#000000" ]
    beardChance: 0.1

# Equipment

- type: entity
  parent: RMCMarineHelmetBase
  id: AU14UNISCM11Helmet
  name: UNISC M11 Helmet
  description: A slightly fancier helmet for UNISC leadership. This one contains a small built-in camera and has cushioning to project your fragile brain.
  components:
  - type: Sprite
    sprite: _AU14/Clothing/UNISC/m11helmet.rsi
  - type: Clothing
    sprite: _AU14/Clothing/UNISC/m11helmet.rsi

- type: entity
  parent: RMCMarineHelmetBase
  id: AU14UNISCM10Helmet
  name: UNISC M10 Helmet
  description: Standard Issue Helmet used by UNISC. Provides modest protection from bullet and melee attacks at the head. It also has an inbuilt camera allowing for command staff to observe the squad's actions.
  components:
  - type: Sprite
    sprite: _AU14/Clothing/UNISC/m10helmet.rsi
  - type: Clothing
    sprite: _AU14/Clothing/UNISC/m10helmet.rsi

- type: entity
  parent: AU14BaseArmor
  id: AU14ArmorM3UNISC
  name: light UNISC armor
  description: Armor.
  components:
  - type: Sprite
    sprite: _AU14/Clothing/UNISC/lightarmoralt.rsi

- type: entity
  parent: AU14PouchGasMaskBag
  id: AU14PouchGasMaskBagFill
  suffix: Filled
  components:
  - type: StorageFill
    contents:
    - id: CMMaskGas
    - id: CMUGasMaskFilter
    - id: CMUGasMaskFilter
    - id: CMUGasMaskFilter

- type: entity
  parent: CMSatchelMarine
  id: AU14MolleSatchel
  name: M1 MOLLE Satchel
  description: Tactical satchel manufactured by one of the Alphatech subsidiaries. Very lightweight beltbag variant that utilizes UA standard MOLLE fastening systems. Standard issue pack for US army troopers.
  components:
  - type: Sprite
    sprite: _AU14/Clothing/US_Army/Back/molle_satchel.rsi
  - type: ItemCamouflage
    camouflageVariations: {}

- type: entity
  parent: CMSatchel
  id: AU14SatchelCorpsman
  name: corpsman satchel
  description: A sterile satchel used in medical departments.
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Back/corpsmansatchel.rsi

- type: entity
  parent: ClothingHeadBase
  id: AU14UNISCBeret
  name: UNISC Beret
  description: A blue beret with the logo of the United Nations Interstellar Settlement Corps.
  components:
  - type: Sprite
    sprite: _AU14/Clothing/UNISC/beret.rsi
  - type: Clothing
    sprite: _AU14/Clothing/UNISC/beret.rsi

- type: entity
  parent: AU14BeltMedicalUPP
  id: AU14BeltMedicalUPPFullSupportTech
  suffix: Full, GROM
  components:
  - type: StorageFill
    contents:
    - id: CMSurgicalLine
    - id: CMSynthGraft
    - id: CMUPlainTraumaDressing10
    - id: CMUCoagulantPowder
    - id: CMUBurnGel
    - id: CMPillCanisterBicaridine
    - id: CMPillCanisterKelotane

