using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Dropship.GunshipControls;

[GenerateTypedNameReferences]
public sealed partial class GunshipControlsWindow : DefaultWindow
{
    public event Action? NavigationPressed;
    public event Action? WeaponsPressed;

    public GunshipControlsWindow()
    {
        RobustXamlLoader.Load(this);
        Title = "Gunship Controls";

        NavigationButton.OnPressed += _ => NavigationPressed?.Invoke();
        WeaponsButton.OnPressed += _ => WeaponsPressed?.Invoke();
    }
}
