# base
- type: entity
  parent: RMCArmbandBase
  id: CMU14ChevronLACNBase
  abstract: true
  suffix: LACN Chevron
  description: LACN naval rank insignia. The pin leaves a green stain against your lapel, but it matches the Latin Commando uniform so they've yet to revise it.

# ├──[ Enlisted ]────────────────────────────────────────────────────┤

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNSeamanRecruit
  name: sailor chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: CMU14RankLACNSeamanRecruit
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNSeamanApprentice
  name: first class sailor chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: CMU14RankLACNSeamanApprentice
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNSeaman
  name: third class corporal chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_enlisted
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_enlisted
  - type: RankChanger
    rank: CMU14RankLACNSeaman
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNPettyOfficerThirdClass
  name: second class corporal chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_nco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_nco
  - type: RankChanger
    rank: CMU14RankLACNPettyOfficerThirdClass
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNPettyOfficerSecondClass
  name: first class corporal chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_nco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_nco
  - type: RankChanger
    rank: CMU14RankLACNPettyOfficerSecondClass
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNPettyOfficerFirstClass
  name: third class sergeant chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_nco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_nco
  - type: RankChanger
    rank: CMU14RankLACNPettyOfficerFirstClass
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNChiefPettyOfficer
  name: second class sergeant chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_snco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_snco
  - type: RankChanger
    rank: CMU14RankLACNChiefPettyOfficer
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNSeniorChief
  name: first class sergeant chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_snco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_snco
  - type: RankChanger
    rank: CMU14RankLACNSeniorChief
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNMasterChief
  name: master sergeant chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_snco
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_snco
  - type: RankChanger
    rank: CMU14RankLACNMasterChief
    override: true

# ├──[ Officers ]────────────────────────────────────────────────────┤

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNSubEnsign
  name: ensign chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNSubEnsign
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNEnsign
  name: ship of the line lieutenant chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNEnsign
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNLieutenantJuniorGrade
  name: corvette captain chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNLieutenantJuniorGrade
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNLieutenant
  name: frigate captain chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNLieutenant
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNLieutenantCommander
  name: captain chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNLieutenantCommander
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNCommander
  name: counter admiral chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_officer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNCommander
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNCaptain
  name: vice admiral chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_seniorofficer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_officer
  - type: RankChanger
    rank: CMU14RankLACNCaptain
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNRearAdmiral
  name: admiral chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_flagofficer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_flagofficer
  - type: RankChanger
    rank: CMU14RankLACNRearAdmiral
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNViceAdmiral
  name: admiral general chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_flagofficer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_flagofficer
  - type: RankChanger
    rank: CMU14RankLACNViceAdmiral
    override: true

- type: entity
  parent: CMU14ChevronLACNBase
  id: CMU14ChevronLACNAdmiral
  name: captain general of the navy chevron
  components:
  - type: Sprite
    sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
    state: ranks_flagofficer
  - type: UniformAccessory
    playerSprite:
      sprite: _AU14/Clothing/Accessory/Chevrons/universal.rsi
      state: equipped-ranks_flagofficer
  - type: RankChanger
    rank: CMU14RankLACNAdmiral
    override: true