using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Dropship.TacticalLand;

[GenerateTypedNameReferences]
public sealed partial class GunshipPilotTopBar : PanelContainer
{
    private string? _lastEta;
    private string? _lastStage;

    public GunshipPilotTopBar(Action openNavigation)
    {
        RobustXamlLoader.Load(this);
        Navigation.OnPressed += _ => openNavigation();
        Eta.Text = Loc.GetString("cmu-gunship-eta", ("eta", "--"));
        Stage.Text = Loc.GetString("cmu-gunship-stage",
            ("stage", Loc.GetString("cmu-gunship-stage-ready")));
    }

    public void SetViewMode(string mode)
    {
        if (ViewMode.Text != mode)
            ViewMode.Text = mode;
    }

    public void SetFlightStatus(string eta, string stage)
    {
        if (_lastEta != eta)
        {
            _lastEta = eta;
            Eta.Text = Loc.GetString("cmu-gunship-eta", ("eta", eta));
        }

        if (_lastStage != stage)
        {
            _lastStage = stage;
            Stage.Text = Loc.GetString("cmu-gunship-stage", ("stage", stage));
        }
    }
}
