using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._RMC14.Camera;

namespace Content.Client._RMC14.Camera;

[GenerateTypedNameReferences]
public sealed partial class RMCCameraButton : Button
{
    internal RmcCameraRowBinding Binding { get; } = new();

    public RMCCameraButton()
    {
        RobustXamlLoader.Load(this);
    }
}

internal sealed class RmcCameraRowBinding
{
    private NetEntity _camera;

    public void Bind(NetEntity camera)
    {
        _camera = camera;
    }

    public RMCCameraWatchBuiMsg CreateSelectionMessage()
    {
        return new RMCCameraWatchBuiMsg(_camera);
    }
}
