- type: entity
  parent: BaseGameRule
  id: SubvertedSynth
  components:
  - type: SubvertedSynthRule
  - type: AntagSelection
    selectionTime: PostPlayerSpawn
    definitions:
    - prefRoles: [ CLFSubvertedSynthRole ]
