- type: loadout
  id: GlassesMedicalHUDGlassesAU14
  storage:
    back:
    - RMCGlassesMedicalHUDGlasses

- type: loadout
  id: GlassesSecurityHUDGlassesAU14
  storage:
    back:
    - RMCGlassesHUDSecurity

- type: loadout
  id: GlassesReagentHUDGlassesAU14
  storage:
    back:
    - RMCGlassesReagentHUDGlasses
