- type: job
  parent: CMJobXenoBase
  id: CMU14JobPathogenConditor
  name: cmu-job-name-pathogen-conditor
  playTimeTracker: CMU14JobPathogenConditor
 
- type: playTimeTracker
  id: CMU14JobPathogenConditor
  isXeno: true